### ISSUE TITLE
Missing $KNOX_HOME

### ISSUE THREAD

**Issue by AliGouta** [opencore/knox-cloudera#9]
I am trying to install knox 1.2.0 parcel on Cloudera. Turns out that during the Bootstrap configuration, the variable $KNOX_HOME is empty (c.f. last line).

```
Current working directory: /run/cloudera-scm-agent/process/298-knox-KNOX_GATEWAY-GatewayCreateConfigDirectory
Launching one-off process: /usr/lib64/cmf/service/csd/csd.sh /var/lib/knox/conf
Fri May 31 19:06:55 CEST 2019
JAVA_HOME=/usr/java/jdk1.8.0_66
Using -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/knox_knox-KNOX_GATEWAY-99513813285e94d16c8ae6a2ea56094b_pid4397.hprof -XX:OnOutOfMemoryError=/usr/lib64/cmf/service/common/killparent.sh as CSD_JAVA_OPTS
Using /run/cloudera-scm-agent/process/298-knox-KNOX_GATEWAY-GatewayCreateConfigDirectory as conf dir
Using scripts/bootstrap_config.sh as process script
CONF_DIR=/run/cloudera-scm-agent/process/298-knox-KNOX_GATEWAY-GatewayCreateConfigDirectory
CMF_CONF_DIR=/etc/cloudera-scm-agent
cp -R /conf.org/* /var/lib/knox/conf/
```
the copy command expects the `$KNOX_HOME/conf.org/*`, however, it returns nothing. Any clue ? It might be related to the `knox-csd/scripts/bootstrap_config.sh` script ?

**Comment by lfrancke** [comment]
Not right now I'm afraid.
I can take a look next week

**Comment by AliGouta** [comment]
I just added this task in the `main.yml`:

```- name: Original directories should be accessible by user knox
  file:
    path: "{{ WORK_DIR }}/{{ PARCEL_PREFIX }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes```

This gives the possibility to user `knox` to load env variables and let everything works as expected.
Thanks !

**Comment by lfrancke** [comment]
Great! Sorry, I didn't get around to this. Would you like to create a pull request?

**Comment by calloc** [comment]
@AliGouta  Hi I ran into the same problem. What did you do to resolve? Thanks in advance.

**Comment by AliGouta** [comment]
@calloc, I created a fork of this project and made a fix + other patches I think. I did not really create a PR on this repository. Hope I can do it when I have sometime.

**Comment by lfrancke** [comment]
Yes, I'm sorry. We're not actually using this Parcel anymore I'm afraid.
Happy to accept Pull Requests though.
